apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
spec:
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: cert
  dnsNames:
  - reto4.web.com