apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: nfs
              mountPath: /var/www/html
          env:
            - name: WORDPRESS_DB_HOST
              value: ip-db
            - name: WORDPRESS_DB_PASSWORD
              value: password
            - name: WORDPRESS_DB_USER
              value: admin
            - name: WORDPRESS_DB_NAME
              value: db
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
kind: Service
apiVersion: v1
metadata:
  name: wordpress-service
spec:
  ports:
    - port: 80
  selector:
    app: wordpress